package  com.ss.entity;

// Generated 2011-3-23 11:09:37 by Hibernate Tools 3.2.2.GA

/**
 * SysAuthoritiesResources generated by hbm2java
 */
public class SysAuthorityResource implements java.io.Serializable {

	private long id;
	private SysAuthority sysAuthority;
	private SysResource sysResource;
	private Boolean enabled;

	public SysAuthorityResource() {
	}

	public SysAuthorityResource(long id) {
		this.id = id;
	}

	public SysAuthorityResource(long id, SysAuthority sysAuthorities,
			SysResource sysResources, Boolean enabled) {
		this.id = id;
		this.sysAuthority = sysAuthorities;
		this.sysResource = sysResources;
		this.enabled = enabled;
	}

	public SysAuthority getSysAuthority() {
		return sysAuthority;
	}

	public void setSysAuthority(SysAuthority sysAuthority) {
		this.sysAuthority = sysAuthority;
	}

	public SysResource getSysResource() {
		return sysResource;
	}

	public void setSysResource(SysResource sysResource) {
		this.sysResource = sysResource;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public SysAuthority getSysAuthorities() {
		return this.sysAuthority;
	}

	public void setSysAuthorities(SysAuthority sysAuthorities) {
		this.sysAuthority = sysAuthorities;
	}

	public SysResource getSysResources() {
		return this.sysResource;
	}

	public void setSysResources(SysResource sysResources) {
		this.sysResource = sysResources;
	}

	public Boolean getEnabled() {
		return this.enabled;
	}

	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}

}
