package com.ss.entity;

// Generated 2011-3-23 11:09:37 by Hibernate Tools 3.2.2.GA

/**
 * PubRolesAuthorities generated by hbm2java
 */
public class SysRoleAuthority implements java.io.Serializable {

	private long id;
	private SysAuthority sysAuthority;
	private SysRole sysRole;
//	
//	private String roleId;
//	
//	private String authorityId;
	
	private Boolean enabled;

	public SysRoleAuthority() {
	}

	public SysRoleAuthority(long id) {
		this.id = id;
	}

	public SysRoleAuthority(long id, SysAuthority sysAuthorities,
			SysRole sysRoles, Boolean enabled) {
		this.id = id;
		this.sysAuthority = sysAuthorities;
		this.sysRole = sysRoles;
		this.enabled = enabled;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}



	public SysAuthority getSysAuthority() {
		return sysAuthority;
	}

	public void setSysAuthority(SysAuthority sysAuthority) {
		this.sysAuthority = sysAuthority;
	}

	public SysRole getSysRole() {
		return sysRole;
	}

	public void setSysRole(SysRole sysRole) {
		this.sysRole = sysRole;
	}

	public Boolean getEnabled() {
		return this.enabled;
	}

	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}
	
//	public String getRoleId(){
//		return roleId;
//	}
//	
//	public void setRoleId( String roleId ){
//		this.roleId = roleId;
//	}
//	
//	public String getAuthorityId(){
//		return authorityId;
//	}
//	
//	public void setAuthorityId( String authorityId ){
//		this.authorityId = authorityId;
//	}

}
