package com.ss.entity;

// Generated 2011-3-23 11:09:37 by Hibernate Tools 3.2.2.GA

import java.util.HashMap;
import java.util.HashSet;
import java.util.Set;

/**
 * PubRoles generated by hbm2java
 */
public class SysRole implements java.io.Serializable {


	private static final long serialVersionUID = 8069033086159154327L;
	
	private String id;
	private String name;
	private String description;
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public void setSysUserRole(Set<?> sysUsersRoles) {
		this.sysUserRole = sysUsersRoles;
	}

	public void setSysRoleAuthority(Set<?> sysRolesAuthorities) {
		this.sysRoleAuthority = sysRolesAuthorities;
	}

	public Set<?> getSysUserRole() {
		return sysUserRole;
	}

	public Set<?> getSysRoleAuthority() {
		return sysRoleAuthority;
	}

	private Boolean enabled;
	private Boolean issys;
	
	//
	private String module;
	
	private Set<?> sysUserRole = new HashSet(0);
	private Set<?> sysRoleAuthority = new HashSet(0);

	public SysRole() {
	}

	public SysRole(String roleId) {
		this.id = roleId;
	}
	
	public SysRole(String roleId, String roleName, String roleDesc) {
		this.id = roleId;
		this.name = roleName;
		this.description = roleDesc;
	}
	
	public SysRole(String roleId, String roleName, String roleDesc,
			Boolean enabled, Boolean issys, String module) {
		this.id = roleId;
		this.name = roleName;
		this.description = roleDesc;
		this.enabled = enabled;
		this.issys = issys;
		this.module = module;
	}

	public SysRole(String roleId, String roleName, String roleDesc,
			Boolean enabled, Boolean issys, String module, Set sysUsersRoles,
			Set sysRolesAuthorities) {
		this.id = roleId;
		this.name = roleName;
		this.description = roleDesc;
		this.enabled = enabled;
		this.issys = issys;
		this.module = module;
		this.sysUserRole = sysUsersRoles;
		this.sysRoleAuthority = sysRolesAuthorities;
	}

	public String getRoleId() {
		return this.id;
	}

	public void setRoleId(String roleId) {
		this.id = roleId;
	}

	public String getRoleName() {
		return this.name;
	}

	public void setRoleName(String roleName) {
		this.name = roleName;
	}

	public String getRoleDesc() {
		return this.description;
	}

	public void setRoleDesc(String roleDesc) {
		this.description = roleDesc;
	}

	public Boolean getEnabled() {
		return this.enabled;
	}

	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}

	public Boolean getIssys() {
		return this.issys;
	}

	public void setIssys(Boolean issys) {
		this.issys = issys;
	}
	
	
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}
	
	
	/*
	 * ��Ҫ�ѳ־����ʵ�����Set��(�����ʾ��ֵ����ʱ)���������ѹ�ʵ��
	 * ��Ҫ��д�ó־����equals��hashCode��
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	public boolean equals( Object other ){
		
		if( this == other ) return true;
		
		if( !( other instanceof SysRole ) ) return false;
		
		final SysRole sysRoles = (SysRole)other;
		
		if( !sysRoles.getRoleName().equals( getRoleName() ) ) return false;
		
		if( !sysRoles.getRoleDesc().equals( getRoleDesc())) return false;
		
		return true;
		
	}
	
	/*
	 * ��дhashCode()��
	 * @see java.lang.Object#hashCode()
	 */
	public int hashCode(){
		
		int result;
		
		result = getRoleName().hashCode();
		
		result = 29 * result + getRoleDesc().hashCode();
		
		return result;
	}
	
	public static void main(String[] args){
		
		SysRole role1 = new SysRole("1","lxb","ljh");
		SysRole role2 = new SysRole("1","lxb","ljh");
		
		/*
		 * �������飬������дequals��hashCodeʱ��ʾΪfalse;
		 * ��дʱ����ʾΪtrue��
		 * �����Ϊʲô��дequals��hashCode��ԭ�򣬵���ϣ���hiberate����ȡ�Ķ���ʵ���У�
		 * �������е��ֶε����ݶ���ͬʱ������Ϊ����������ʵ������ͬ�ģ���ʱ����Ҫ��дequals��hashCode��
		 * ��дequals��hashCode��ζ�ţ������ڲ�ͬ�����ļ�Session�е�����ʵ���������ȷ�������塣
		 */
		System.out.println(role1.equals(role2));
		
		/*
		 * �������飬������дequals��hashCodeʱ��ʾΪfalse;
		 * ��дʱ����ʾΪtrue��
		 * 
		 */
		System.out.println(role1.hashCode() == role2.hashCode());
		
	}
	
}
