package com.ss.entity;

// Generated 2011-3-23 11:09:37 by Hibernate Tools 3.2.2.GA

/**
 * PubUsersRoles generated by hbm2java
 */
public class SysUserRole implements java.io.Serializable {

	private long id;
	private SysUser pubUsers;
	private SysRole pubRoles;
	private Boolean enabled;

	public SysUserRole() {
	}

	public SysUser getPubUsers() {
		return pubUsers;
	}

	public void setPubUsers(SysUser pubUsers) {
		this.pubUsers = pubUsers;
	}

	public SysRole getPubRoles() {
		return pubRoles;
	}

	public void setPubRoles(SysRole pubRoles) {
		this.pubRoles = pubRoles;
	}

	public SysUserRole(long id) {
		this.id = id;
	}

	public SysUserRole(long id, SysUser pubUsers, SysRole pubRoles,
			Boolean enabled) {
		this.id = id;
		this.pubUsers = pubUsers;
		this.pubRoles = pubRoles;
		this.enabled = enabled;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public SysUser getSysUser() {
		return this.pubUsers;
	}

	public void setSysUser(SysUser pubUsers) {
		this.pubUsers = pubUsers;
	}

	public SysRole getSysRole() {
		return this.pubRoles;
	}

	public void setSysRole(SysRole pubRoles) {
		this.pubRoles = pubRoles;
	}

	public Boolean getEnabled() {
		return this.enabled;
	}

	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}

}
